# Generated by Django 6.0.2 on 2026-02-24 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0002_remove_client_assigned_to_remove_client_created_by_and_more'),
        ('Purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='Clients.survivor'),
        ),
    ]
