# Generated by Django 6.0.2 on 2026-02-24 16:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0003_delete_client_delete_contact'),
        ('Products', '0002_alter_category_options_alter_product_options_and_more'),
        ('Purchases', '0002_alter_purchase_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rescue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.localdate, help_text='Date the rescue operation took place')),
                ('outcome', models.CharField(choices=[('successful', 'Successful Rescue'), ('hospitalized', 'Rescued – Hospitalisation Required'), ('unsuccessful', 'Unsuccessful – Fatality'), ('false_alarm', 'False Alarm / Hoax'), ('ongoing', 'Operation Ongoing')], default='ongoing', help_text='Final outcome of the rescue operation', max_length=20)),
                ('equipment_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('equipment_quantity', models.PositiveIntegerField(default=1, help_text='Number of units of this equipment deployed')),
                ('notes', models.TextField(blank=True, help_text='Operational notes or after-action remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(help_text='Primary equipment item deployed during this operation', on_delete=django.db.models.deletion.PROTECT, related_name='rescues', to='Products.product')),
                ('survivor', models.ForeignKey(help_text='Survivor assisted during this operation', on_delete=django.db.models.deletion.PROTECT, related_name='rescues', to='Clients.survivor')),
            ],
            options={
                'verbose_name': 'Rescue Operation',
                'verbose_name_plural': 'Rescue Operations',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
