# Generated by Django 6.0.2 on 2026-02-21 14:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pracownik',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('aktywny', 'Aktywny'), ('nieaktywny', 'Nieaktywny'), ('urlop', 'Na urlopie'), ('zwolniony', 'Zwolniony'), ('staz', 'Staż')], default='aktywny', max_length=20)),
                ('dzial', models.CharField(blank=True, choices=[('it', 'IT'), ('hr', 'HR'), ('finanse', 'Finanse'), ('sprzedaz', 'Sprzedaż'), ('marketing', 'Marketing'), ('operacje', 'Operacje'), ('zarzad', 'Zarząd'), ('logistyka', 'Logistyka'), ('inny', 'Inny')], default='inny', max_length=50)),
                ('rodzaj_zatrudnienia', models.CharField(choices=[('etat', 'Pełny etat'), ('czesc_etatu', 'Część etatu'), ('kontrakt', 'Kontrakt'), ('staz', 'Staż'), ('b2b', 'B2B')], default='etat', max_length=20)),
                ('stanowisko', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('data_zatrudnienia', models.DateField(blank=True, null=True)),
                ('data_zwolnienia', models.DateField(blank=True, null=True)),
                ('wynagrodzenie', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pracownicy', to=settings.AUTH_USER_MODEL)),
                ('przelozony', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='podwladni', to='Pracownicy.pracownik')),
            ],
            options={
                'verbose_name': 'Pracownik',
                'verbose_name_plural': 'Pracownicy',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='KontaktAwaryjny',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('relacja', models.CharField(blank=True, help_text='np. Małżonek, Rodzic, Brat', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('is_primary', models.BooleanField(default=False, help_text='Główny kontakt awaryjny')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pracownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kontakty_awaryjne', to='Pracownicy.pracownik')),
            ],
            options={
                'verbose_name': 'Kontakt awaryjny',
                'verbose_name_plural': 'Kontakty awaryjne',
                'ordering': ['-is_primary', 'last_name'],
            },
        ),
    ]
