# Generated by Django 6.0.2 on 2026-02-24 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0002_remove_client_assigned_to_remove_client_created_by_and_more'),
        ('Purchases', '0002_alter_purchase_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
